//
// CallbackObject.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CallbackObject: JSONEncodable {

    /** URL of webhook, where the event is emitted to. Note: The listener supports both HTTP &amp; HTTPS, we highly recommend that users use HTTPS on all callbacks (with user name and password) to ensure no one may send malicious events pretending to be Phone.com. */
    public var url: String?
    /** Role of callback: main or backup */
    public var role: String?
    /** HTTP method: get or post */
    public var verb: String?
    /** Optional user name needed to logon to the webhook URL */
    public var username: String?
    /** Optional password needed to logon to the webhook URL */
    public var password: String?
    /** Optional : Duration of HTTP response will time out while sending the event to the callback URL. (1 - 10 seconds) */
    public var timeout: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["url"] = self.url
        nillableDictionary["role"] = self.role
        nillableDictionary["verb"] = self.verb
        nillableDictionary["username"] = self.username
        nillableDictionary["password"] = self.password
        nillableDictionary["timeout"] = self.timeout?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
