//
// CallLogFull.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Full Call Log Object includes the properties in the Call Log Summary Object, along with the following: */
open class CallLogFull: JSONEncodable {

    /** ID */
    public var id: String?
    /** Internal system id, may be null */
    public var uuid: String?
    /** Account extension */
    public var _extension: ExtensionSummary?
    /** Call made from this phone number */
    public var callerId: String?
    /** Call made to this phone number */
    public var calledNumber: String?
    /** Call start time */
    public var startTime: String?
    /** Call log creation time. Same as call end time + time needed to create call log */
    public var createdAt: String?
    /** Call direction: in or out */
    public var direction: String?
    /** Call type: call, fax, audiogram ... */
    public var type: String?
    /** Call duration in seconds */
    public var callDuration: Int32?
    /** Was call being monitored? */
    public var isMonitored: String?
    /** Internal system call reference number */
    public var callNumber: String?
    /** Last action of call flow */
    public var finalAction: String?
    /** URL of voicemail if available. User may download the audio via this URL. Empty string if voicemail does not exist */
    public var voicemailUrl: String?
    /** URL of voicemail if available. User may listen to the audio online via this URL. Empty string if voicemail does not exist */
    public var voicemailCpUrl: String?
    /** Transcript of voicemail if enabled and available */
    public var voicemailTranscript: String?
    /** URL of call recording if available. User may download the audio via this URL. Empty string if call recording does not exist */
    public var callRecordingUrl: String?
    /** URL of call recording if available. User may listen to the audio online via this URL. Empty string if call recording does not exist */
    public var callRecordingCpUrl: String?
    /** A list of call flows from beginning of call to end of call. */
    public var details: [CallDetails]?
    /** Internal system caller id / name */
    public var callerCnam: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["uuid"] = self.uuid
        nillableDictionary["extension"] = self._extension?.encodeToJSON()
        nillableDictionary["caller_id"] = self.callerId
        nillableDictionary["called_number"] = self.calledNumber
        nillableDictionary["start_time"] = self.startTime
        nillableDictionary["created_at"] = self.createdAt
        nillableDictionary["direction"] = self.direction
        nillableDictionary["type"] = self.type
        nillableDictionary["call_duration"] = self.callDuration?.encodeToJSON()
        nillableDictionary["is_monitored"] = self.isMonitored
        nillableDictionary["call_number"] = self.callNumber
        nillableDictionary["final_action"] = self.finalAction
        nillableDictionary["voicemail_url"] = self.voicemailUrl
        nillableDictionary["voicemail_cp_url"] = self.voicemailCpUrl
        nillableDictionary["voicemail_transcript"] = self.voicemailTranscript
        nillableDictionary["call_recording_url"] = self.callRecordingUrl
        nillableDictionary["call_recording_cp_url"] = self.callRecordingCpUrl
        nillableDictionary["details"] = self.details?.encodeToJSON()
        nillableDictionary["caller_cnam"] = self.callerCnam

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
