//
// CreateListenerParams.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CreateListenerParams: JSONEncodable {

    /** Type of listener. Must be &#39;callback&#39; */
    public var type: String?
    /** Type of event to subscribe. &#39;call.new&#39;, &#39;call.update&#39;, &#39;call.complete&#39; */
    public var eventType: String?
    /** Array of Callback Objects. */
    public var callbacks: [CallbackObject]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["type"] = self.type
        nillableDictionary["event_type"] = self.eventType
        nillableDictionary["callbacks"] = self.callbacks?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
