//
// CreateOauthParams.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CreateOauthParams: JSONEncodable {

    /** authorization_code, client_credentials, password or refresh_token */
    public var grantType: String?
    /** Client ID */
    public var clientId: String?
    /** Client Secret Key */
    public var clientSecret: String?
    /** Authorization Code created via the /oauth/authorization API */
    public var code: String?
    /** The redirect URI where user enters authentication information */
    public var redirectUri: String?
    /** account-owner, extension-user and/or methods:ALL, separated by space (%20) */
    public var scope: String?
    /** User name */
    public var username: String?
    /** Password */
    public var password: String?
    /** Refresh token */
    public var refreshToken: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["grant_type"] = self.grantType
        nillableDictionary["client_id"] = self.clientId
        nillableDictionary["client_secret"] = self.clientSecret
        nillableDictionary["code"] = self.code
        nillableDictionary["redirect_uri"] = self.redirectUri
        nillableDictionary["scope"] = self.scope
        nillableDictionary["username"] = self.username
        nillableDictionary["password"] = self.password
        nillableDictionary["refresh_token"] = self.refreshToken

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
