//
// FilterVoicemailArray.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class FilterVoicemailArray: JSONEncodable {

    public var id: String?
    public var from: String?
    public var to: String?
    public var isNew: String?
    public var createdAt: Int32?
    public var _extension: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["from"] = self.from
        nillableDictionary["to"] = self.to
        nillableDictionary["is_new"] = self.isNew
        nillableDictionary["created_at"] = self.createdAt?.encodeToJSON()
        nillableDictionary["extension"] = self._extension

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
