//
// GetOauthAccessToken.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class GetOauthAccessToken: JSONEncodable {

    public var scope: String?
    public var expiresAt: Int32?
    public var scopeDetails: [ScopeDetails]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["scope"] = self.scope
        nillableDictionary["expires_at"] = self.expiresAt?.encodeToJSON()
        nillableDictionary["scope_details"] = self.scopeDetails?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
