//
// ListenerFull.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Listener Object is used to represent a listener. Here are the properties: */
open class ListenerFull: JSONEncodable {

    /** Integer ID. Read-only. */
    public var id: Int32?
    public var voipId: Int32?
    /** Type of listener: callback */
    public var type: String?
    /** Type of event subscribed by the listener: call.new, call.update, call.complete, call.log, sms.in, sms.out */
    public var eventType: String?
    /** Array of Callback Object */
    public var callbacks: [Any]?
    public var updatedAt: Int32?
    public var createdAt: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["voip_id"] = self.voipId?.encodeToJSON()
        nillableDictionary["type"] = self.type
        nillableDictionary["event_type"] = self.eventType
        nillableDictionary["callbacks"] = self.callbacks?.encodeToJSON()
        nillableDictionary["updated_at"] = self.updatedAt?.encodeToJSON()
        nillableDictionary["created_at"] = self.createdAt?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
