//
// OauthClientRedirectUriFull.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An OAuth Client Full Object is identical as a Summary Object. */
open class OauthClientRedirectUriFull: JSONEncodable {

    /** OAuth Client Redirect URI ID */
    public var id: Int32?
    /** Client details */
    public var client: OauthClientFull?
    /** Redirect URI details */
    public var redirectUri: RedirectUriFull?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["client"] = self.client?.encodeToJSON()
        nillableDictionary["redirect_uri"] = self.redirectUri?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
