//
// OauthAccessToken.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class OauthAccessToken: JSONEncodable {

    public var accessToken: String?
    public var tokenType: String?
    public var scope: String?
    public var refreshToken: String?
    public var expiresIn: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["access_token"] = self.accessToken
        nillableDictionary["token_type"] = self.tokenType
        nillableDictionary["scope"] = self.scope
        nillableDictionary["refresh_token"] = self.refreshToken
        nillableDictionary["expires_in"] = self.expiresIn?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
