//
// PaymentSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Payment Method Summary Object is used to briefly represent a Credit Card. It consists of parameters in the table below: */
open class PaymentSummary: JSONEncodable {

    /** Payment Method ID */
    public var id: Int32?
    /** API Account ID */
    public var voipId: Int32?
    /** &#39;primary&#39; &#x3D; primary card used for billing; &#39;onfile&#39; &#x3D; card on file; &#39;hidden&#39; &#x3D; deleted card; */
    public var status: String?
    /** Name of Card */
    public var nickname: String?
    /** &#39;cc&#39; for credit card */
    public var type: String?
    /** Time payment record is created */
    public var createdAt: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["voip_id"] = self.voipId?.encodeToJSON()
        nillableDictionary["status"] = self.status
        nillableDictionary["nickname"] = self.nickname
        nillableDictionary["type"] = self.type
        nillableDictionary["created_at"] = self.createdAt?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
