//
// PaymentFull.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Payment Method Full Object contains the same properties as the Payment Method Summary Object, along with the following: */
open class PaymentFull: JSONEncodable {

    /** Payment Method ID */
    public var id: Int32?
    /** API Account ID */
    public var voipId: Int32?
    /** &#39;primary&#39; &#x3D; primary card used for billing; &#39;onfile&#39; &#x3D; card on file; &#39;hidden&#39; &#x3D; deleted card; */
    public var status: String?
    /** Name of Card */
    public var nickname: String?
    /** &#39;cc&#39; for credit card */
    public var type: String?
    /** Time payment record is created */
    public var createdAt: Int32?
    /** Detail of contact person */
    public var contact: ContactResponse?
    /** Number of times the payment method was declined */
    public var declineCount: Int32?
    /** Next billing date */
    public var nextChargeDate: Int32?
    /** Last time the payment method was updated */
    public var updatedAt: Int32?
    /** Encrypted credit card token to be used for billing */
    public var ccToken: String?
    /** Credit card number partially masked with xxxxxxxx */
    public var ccNumber: String?
    /** Credit card expiration date */
    public var ccExp: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["voip_id"] = self.voipId?.encodeToJSON()
        nillableDictionary["status"] = self.status
        nillableDictionary["nickname"] = self.nickname
        nillableDictionary["type"] = self.type
        nillableDictionary["created_at"] = self.createdAt?.encodeToJSON()
        nillableDictionary["contact"] = self.contact?.encodeToJSON()
        nillableDictionary["decline_count"] = self.declineCount?.encodeToJSON()
        nillableDictionary["next_charge_date"] = self.nextChargeDate?.encodeToJSON()
        nillableDictionary["updated_at"] = self.updatedAt?.encodeToJSON()
        nillableDictionary["cc_token"] = self.ccToken
        nillableDictionary["cc_number"] = self.ccNumber
        nillableDictionary["cc_exp"] = self.ccExp

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
