//
// ReplaceExtensionParams.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ReplaceExtensionParams: JSONEncodable {

    public var voicemail: VoicemailInput?
    public var callNotifications: CallNotifications?
    /** Recording lookup object */
    public var nameGreeting: Any?
    /** Name (required) */
    public var name: String?
    /** Timezone */
    public var timezone: String?
    /** Include in dial-by-name directory */
    public var includeInDirectory: String?
    /** Extension number (required) */
    public var _extension: Int32?
    /** Enable outgoing calls */
    public var enableOutboundCalls: String?
    /** Extension type */
    public var usageType: String?
    /** Contact name */
    public var fullName: String?
    /** Enable Call Waiting */
    public var enableCallWaiting: String?
    /** Caller ID */
    public var callerId: String?
    /** Local area code */
    public var localAreaCode: String?
    /** Route object lookup (must belong to this extension) */
    public var route: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["voicemail"] = self.voicemail?.encodeToJSON()
        nillableDictionary["call_notifications"] = self.callNotifications?.encodeToJSON()
        nillableDictionary["name_greeting"] = self.nameGreeting
        nillableDictionary["name"] = self.name
        nillableDictionary["timezone"] = self.timezone
        nillableDictionary["include_in_directory"] = self.includeInDirectory
        nillableDictionary["extension"] = self._extension?.encodeToJSON()
        nillableDictionary["enable_outbound_calls"] = self.enableOutboundCalls
        nillableDictionary["usage_type"] = self.usageType
        nillableDictionary["full_name"] = self.fullName
        nillableDictionary["enable_call_waiting"] = self.enableCallWaiting
        nillableDictionary["caller_id"] = self.callerId
        nillableDictionary["local_area_code"] = self.localAreaCode
        nillableDictionary["route"] = self.route

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
