//
// VoicemailFull.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Full Voicemail Object includes all of the properties in the Voicemail Summary Object. */
open class VoicemailFull: JSONEncodable {

    /** Unique Voicemail ID. Read-only. */
    public var id: String?
    /** Name. Required. */
    public var downloadUrl: String?
    /** Extension where the voicemail is saved into. */
    public var _extension: ExtensionSummary?
    /** The caller&#39;s information */
    public var from: FromObject?
    /** The phone number where the caller is calling */
    public var to: String?
    /** True when Voicemail is new; False when Voicemail has been listened */
    public var isNew: Bool?
    /** Date string representing the UTC time that the object was created in the Phone.com API system. */
    public var createdAt: Int32?
    /** Folder name where voicemail is saved */
    public var folder: String?
    /** Length of voicemail in seconds */
    public var duration: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["download_url"] = self.downloadUrl
        nillableDictionary["extension"] = self._extension?.encodeToJSON()
        nillableDictionary["from"] = self.from?.encodeToJSON()
        nillableDictionary["to"] = self.to
        nillableDictionary["is_new"] = self.isNew
        nillableDictionary["created_at"] = self.createdAt?.encodeToJSON()
        nillableDictionary["folder"] = self.folder
        nillableDictionary["duration"] = self.duration?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
