//
// CalllogsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class CalllogsAPI: APIBase {
    /**
     Show details of an individual Call Log entry
     
     - parameter accountId: (path) Account ID 
     - parameter callId: (path) Call ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAccountCallLogs(accountId: Int32, callId: String, completion: @escaping ((_ data: CallLogFull?,_ error: Error?) -> Void)) {
        getAccountCallLogsWithRequestBuilder(accountId: accountId, callId: callId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Show details of an individual Call Log entry
     - GET /accounts/{account_id}/call-logs/{call_id}
     - Show details of an individual Call Log entry. See Call Logs for more detail.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "call_number" : "aeiou",
  "extension" : {
    "extension" : 6,
    "name" : "aeiou",
    "id" : 0
  },
  "caller_cnam" : "aeiou",
  "voicemail_cp_url" : "aeiou",
  "created_at" : "aeiou",
  "type" : "aeiou",
  "uuid" : "aeiou",
  "call_duration" : 1,
  "final_action" : "aeiou",
  "start_time" : "aeiou",
  "call_recording_url" : "aeiou",
  "is_monitored" : "aeiou",
  "caller_id" : "aeiou",
  "voicemail_transcript" : "aeiou",
  "details" : [ {
    "start_time" : 5,
    "voip_phone_id" : 7,
    "type" : "aeiou",
    "id_value" : 5,
    "voip_id" : 2
  } ],
  "id" : "aeiou",
  "called_number" : "aeiou",
  "voicemail_url" : "aeiou",
  "call_recording_cp_url" : "aeiou",
  "direction" : "aeiou"
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter callId: (path) Call ID 

     - returns: RequestBuilder<CallLogFull> 
     */
    open class func getAccountCallLogsWithRequestBuilder(accountId: Int32, callId: String) -> RequestBuilder<CallLogFull> {
        var path = "/accounts/{account_id}/call-logs/{call_id}"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{call_id}", with: "\(callId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CallLogFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get a list of call details associated with your account
     
     - parameter accountId: (path) Account ID 
     - parameter filtersId: (query) ID filter (optional)
     - parameter filtersStartTime: (query) Call start time filter (optional)
     - parameter filtersCreatedAt: (query) Call log creation time filter (optional)
     - parameter filtersDirection: (query) Call direction filter: in or out (optional)
     - parameter filtersCalledNumber: (query) Called number (optional)
     - parameter filtersType: (query) Call type, such as &#39;call&#39;, &#39;fax&#39;, &#39;audiogram&#39; (optional)
     - parameter filtersExtension: (query) Extension filter (optional)
     - parameter sortId: (query) ID sorting (optional)
     - parameter sortStartTime: (query) Sorting by call start time: asc or desc (optional)
     - parameter sortCreatedAt: (query) Sorting by call log creation time: asc or desc (optional)
     - parameter limit: (query) Max results (optional)
     - parameter offset: (query) Results to skip (optional)
     - parameter fields: (query) Field set (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listAccountCallLogs(accountId: Int32, filtersId: [String]? = nil, filtersStartTime: [String]? = nil, filtersCreatedAt: String? = nil, filtersDirection: String? = nil, filtersCalledNumber: String? = nil, filtersType: String? = nil, filtersExtension: [String]? = nil, sortId: String? = nil, sortStartTime: String? = nil, sortCreatedAt: String? = nil, limit: Int32? = nil, offset: Int32? = nil, fields: String? = nil, completion: @escaping ((_ data: ListCallLogs?,_ error: Error?) -> Void)) {
        listAccountCallLogsWithRequestBuilder(accountId: accountId, filtersId: filtersId, filtersStartTime: filtersStartTime, filtersCreatedAt: filtersCreatedAt, filtersDirection: filtersDirection, filtersCalledNumber: filtersCalledNumber, filtersType: filtersType, filtersExtension: filtersExtension, sortId: sortId, sortStartTime: sortStartTime, sortCreatedAt: sortCreatedAt, limit: limit, offset: offset, fields: fields).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get a list of call details associated with your account
     - GET /accounts/{account_id}/call-logs
     - Get a list of call details associated with your account. See Call Logs for more detail.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "total" : 0,
  "offset" : 6,
  "limit" : 1,
  "filters" : {
    "start_time" : "aeiou",
    "created_at" : "aeiou",
    "id" : "aeiou",
    "called_number" : "aeiou",
    "type" : "aeiou",
    "direction" : "aeiou"
  },
  "sort" : {
    "start_time" : "aeiou",
    "created_at" : "aeiou",
    "id" : "aeiou"
  },
  "items" : [ {
    "call_number" : "aeiou",
    "extension" : {
      "extension" : 5,
      "name" : "aeiou",
      "id" : 5
    },
    "caller_cnam" : "aeiou",
    "voicemail_cp_url" : "aeiou",
    "created_at" : "aeiou",
    "type" : "aeiou",
    "uuid" : "aeiou",
    "call_duration" : 2,
    "final_action" : "aeiou",
    "start_time" : "aeiou",
    "call_recording_url" : "aeiou",
    "is_monitored" : "aeiou",
    "caller_id" : "aeiou",
    "voicemail_transcript" : "aeiou",
    "details" : [ {
      "start_time" : 7,
      "voip_phone_id" : 2,
      "type" : "aeiou",
      "id_value" : 9,
      "voip_id" : 3
    } ],
    "id" : "aeiou",
    "called_number" : "aeiou",
    "voicemail_url" : "aeiou",
    "call_recording_cp_url" : "aeiou",
    "direction" : "aeiou"
  } ]
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter filtersId: (query) ID filter (optional)
     - parameter filtersStartTime: (query) Call start time filter (optional)
     - parameter filtersCreatedAt: (query) Call log creation time filter (optional)
     - parameter filtersDirection: (query) Call direction filter: in or out (optional)
     - parameter filtersCalledNumber: (query) Called number (optional)
     - parameter filtersType: (query) Call type, such as &#39;call&#39;, &#39;fax&#39;, &#39;audiogram&#39; (optional)
     - parameter filtersExtension: (query) Extension filter (optional)
     - parameter sortId: (query) ID sorting (optional)
     - parameter sortStartTime: (query) Sorting by call start time: asc or desc (optional)
     - parameter sortCreatedAt: (query) Sorting by call log creation time: asc or desc (optional)
     - parameter limit: (query) Max results (optional)
     - parameter offset: (query) Results to skip (optional)
     - parameter fields: (query) Field set (optional)

     - returns: RequestBuilder<ListCallLogs> 
     */
    open class func listAccountCallLogsWithRequestBuilder(accountId: Int32, filtersId: [String]? = nil, filtersStartTime: [String]? = nil, filtersCreatedAt: String? = nil, filtersDirection: String? = nil, filtersCalledNumber: String? = nil, filtersType: String? = nil, filtersExtension: [String]? = nil, sortId: String? = nil, sortStartTime: String? = nil, sortCreatedAt: String? = nil, limit: Int32? = nil, offset: Int32? = nil, fields: String? = nil) -> RequestBuilder<ListCallLogs> {
        var path = "/accounts/{account_id}/call-logs"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "filters[id]": filtersId, 
            "filters[start_time]": filtersStartTime, 
            "filters[created_at]": filtersCreatedAt, 
            "filters[direction]": filtersDirection, 
            "filters[called_number]": filtersCalledNumber, 
            "filters[type]": filtersType, 
            "filters[extension]": filtersExtension, 
            "sort[id]": sortId, 
            "sort[start_time]": sortStartTime, 
            "sort[created_at]": sortCreatedAt, 
            "limit": limit?.encodeToJSON(), 
            "offset": offset?.encodeToJSON(), 
            "fields": fields
        ])
        

        let requestBuilder: RequestBuilder<ListCallLogs>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
