//
// ListenersAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class ListenersAPI: APIBase {
    /**
     Add a listener object to your account that can be used to subscribe an event.
     
     - parameter accountId: (path) Account ID 
     - parameter data: (body) Account Listeners Data (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createAccountListener(accountId: Int32, data: CreateListenerParams? = nil, completion: @escaping ((_ data: ListenerFull?,_ error: Error?) -> Void)) {
        createAccountListenerWithRequestBuilder(accountId: accountId, data: data).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Add a listener object to your account that can be used to subscribe an event.
     - POST /accounts/{account_id}/listeners
     - Add a listener object to your account that can be used to subscribe an event. See Account Listeners for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level Post Listener API with the following definition: POST https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/listeners
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "event_type" : "aeiou",
  "updated_at" : 1,
  "callbacks" : [ "{}" ],
  "created_at" : 5,
  "id" : 0,
  "type" : "aeiou",
  "voip_id" : 6
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter data: (body) Account Listeners Data (optional)

     - returns: RequestBuilder<ListenerFull> 
     */
    open class func createAccountListenerWithRequestBuilder(accountId: Int32, data: CreateListenerParams? = nil) -> RequestBuilder<ListenerFull> {
        var path = "/accounts/{account_id}/listeners"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = data?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ListenerFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Delete an individual event listener.
     
     - parameter accountId: (path) Account ID 
     - parameter listenerId: (path) Listener ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteAccountListener(accountId: Int32, listenerId: Int32, completion: @escaping ((_ data: DeleteEntry?,_ error: Error?) -> Void)) {
        deleteAccountListenerWithRequestBuilder(accountId: accountId, listenerId: listenerId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Delete an individual event listener.
     - DELETE /accounts/{account_id}/listeners/{listener_id}
     - Delete an individual event listener. See Account Listeners for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level Delete Listener API with the following definition: DELETE https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/listeners/:listener_id
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "success" : true
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter listenerId: (path) Listener ID 

     - returns: RequestBuilder<DeleteEntry> 
     */
    open class func deleteAccountListenerWithRequestBuilder(accountId: Int32, listenerId: Int32) -> RequestBuilder<DeleteEntry> {
        var path = "/accounts/{account_id}/listeners/{listener_id}"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{listener_id}", with: "\(listenerId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<DeleteEntry>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Show details of an individual listener.
     
     - parameter accountId: (path) Account ID 
     - parameter listenerId: (path) Listener ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAccountListener(accountId: Int32, listenerId: Int32, completion: @escaping ((_ data: ListenerFull?,_ error: Error?) -> Void)) {
        getAccountListenerWithRequestBuilder(accountId: accountId, listenerId: listenerId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Show details of an individual listener.
     - GET /accounts/{account_id}/listeners/{listener_id}
     - Show details of an individual event listener. See Account Listeners for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level Get Listener API with the following definition: GET https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/listeners/:listener_id
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "event_type" : "aeiou",
  "updated_at" : 1,
  "callbacks" : [ "{}" ],
  "created_at" : 5,
  "id" : 0,
  "type" : "aeiou",
  "voip_id" : 6
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter listenerId: (path) Listener ID 

     - returns: RequestBuilder<ListenerFull> 
     */
    open class func getAccountListenerWithRequestBuilder(accountId: Int32, listenerId: Int32) -> RequestBuilder<ListenerFull> {
        var path = "/accounts/{account_id}/listeners/{listener_id}"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{listener_id}", with: "\(listenerId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ListenerFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get a list of listeners for an account.
     
     - parameter accountId: (path) Account ID 
     - parameter filtersId: (query) ID filter (optional)
     - parameter sortId: (query) ID sorting (optional)
     - parameter limit: (query) Max results (optional)
     - parameter offset: (query) Results to skip (optional)
     - parameter fields: (query) Field set (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listAccountListeners(accountId: Int32, filtersId: [String]? = nil, sortId: String? = nil, limit: Int32? = nil, offset: Int32? = nil, fields: String? = nil, completion: @escaping ((_ data: ListListeners?,_ error: Error?) -> Void)) {
        listAccountListenersWithRequestBuilder(accountId: accountId, filtersId: filtersId, sortId: sortId, limit: limit, offset: offset, fields: fields).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get a list of listeners for an account.
     - GET /accounts/{account_id}/listeners
     - Get a list of listeners for an account. See Account Listeners for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level List Listeners API with the following definition: GET https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/listeners
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "total" : 0,
  "offset" : 1,
  "limit" : 6,
  "filters" : {
    "id" : "aeiou"
  },
  "sort" : {
    "id" : "aeiou"
  },
  "items" : [ {
    "event_type" : "aeiou",
    "updated_at" : 2,
    "callbacks" : [ "{}" ],
    "created_at" : 7,
    "id" : 5,
    "type" : "aeiou",
    "voip_id" : 5
  } ]
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter filtersId: (query) ID filter (optional)
     - parameter sortId: (query) ID sorting (optional)
     - parameter limit: (query) Max results (optional)
     - parameter offset: (query) Results to skip (optional)
     - parameter fields: (query) Field set (optional)

     - returns: RequestBuilder<ListListeners> 
     */
    open class func listAccountListenersWithRequestBuilder(accountId: Int32, filtersId: [String]? = nil, sortId: String? = nil, limit: Int32? = nil, offset: Int32? = nil, fields: String? = nil) -> RequestBuilder<ListListeners> {
        var path = "/accounts/{account_id}/listeners"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "filters[id]": filtersId, 
            "sort[id]": sortId, 
            "limit": limit?.encodeToJSON(), 
            "offset": offset?.encodeToJSON(), 
            "fields": fields
        ])
        

        let requestBuilder: RequestBuilder<ListListeners>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Update the settings of an individual event listener.
     
     - parameter accountId: (path) Account ID 
     - parameter listenerId: (path) Listener ID 
     - parameter data: (body) Account Listeners Data (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func replaceAccountListener(accountId: Int32, listenerId: Int32, data: CreateListenerParams? = nil, completion: @escaping ((_ data: ListenerFull?,_ error: Error?) -> Void)) {
        replaceAccountListenerWithRequestBuilder(accountId: accountId, listenerId: listenerId, data: data).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Update the settings of an individual event listener.
     - PUT /accounts/{account_id}/listeners/{listener_id}
     - Update the settings of an individual event listener. See Event Listeners for more detail. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level Replace Listener API with the following definition: PUT https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/listeners/:listener_id
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "event_type" : "aeiou",
  "updated_at" : 1,
  "callbacks" : [ "{}" ],
  "created_at" : 5,
  "id" : 0,
  "type" : "aeiou",
  "voip_id" : 6
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter listenerId: (path) Listener ID 
     - parameter data: (body) Account Listeners Data (optional)

     - returns: RequestBuilder<ListenerFull> 
     */
    open class func replaceAccountListenerWithRequestBuilder(accountId: Int32, listenerId: Int32, data: CreateListenerParams? = nil) -> RequestBuilder<ListenerFull> {
        var path = "/accounts/{account_id}/listeners/{listener_id}"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{listener_id}", with: "\(listenerId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = data?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ListenerFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
