//
// MediaAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class MediaAPI: APIBase {
    /**
     Add a media object to your account that can be used as a greeting or hold music. Users may create a media by using the built-in Text-to-speech (TTS) facility or upload a file of their choice. (Note: The maximum size for media files or JSON objects included with a POST or PUT request is 10 MB)
     
     - parameter accountId: (path) Account ID 
     - parameter json: (form) Media extra parameters (optional)
     - parameter file: (form) Media file (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createAccountMediaFiles(accountId: Int32, json: String? = nil, file: URL? = nil, completion: @escaping ((_ data: MediaFull?,_ error: Error?) -> Void)) {
        createAccountMediaFilesWithRequestBuilder(accountId: accountId, json: json, file: file).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Add a media object to your account that can be used as a greeting or hold music. Users may create a media by using the built-in Text-to-speech (TTS) facility or upload a file of their choice. (Note: The maximum size for media files or JSON objects included with a POST or PUT request is 10 MB)
     - POST /accounts/{account_id}/media/files
     - See Account Media for more info on the properties.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "name" : "aeiou",
  "id" : 0,
  "type" : "aeiou"
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter json: (form) Media extra parameters (optional)
     - parameter file: (form) Media file (optional)

     - returns: RequestBuilder<MediaFull> 
     */
    open class func createAccountMediaFilesWithRequestBuilder(accountId: Int32, json: String? = nil, file: URL? = nil) -> RequestBuilder<MediaFull> {
        var path = "/accounts/{account_id}/media/files"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let formParams: [String:Any?] = [
            "json": json,
            "file": file
        ]

        let nonNullParameters = APIHelper.rejectNil(formParams)
        let parameters = APIHelper.convertBoolToString(nonNullParameters)

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<MediaFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Add a media object to your account that can be used as a greeting or hold music. Users may create a media by using the built-in Text-to-speech (TTS) facility or upload a file of their choice. (Note: The maximum size for media files or JSON objects included with a POST or PUT request is 10 MB)
     
     - parameter accountId: (path) Account ID 
     - parameter data: (body) Media data (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createAccountMediaTts(accountId: Int32, data: CreateMediaParams? = nil, completion: @escaping ((_ data: MediaFull?,_ error: Error?) -> Void)) {
        createAccountMediaTtsWithRequestBuilder(accountId: accountId, data: data).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Add a media object to your account that can be used as a greeting or hold music. Users may create a media by using the built-in Text-to-speech (TTS) facility or upload a file of their choice. (Note: The maximum size for media files or JSON objects included with a POST or PUT request is 10 MB)
     - POST /accounts/{account_id}/media/tts
     - See Account Media for more info on the properties.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "name" : "aeiou",
  "id" : 0,
  "type" : "aeiou"
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter data: (body) Media data (optional)

     - returns: RequestBuilder<MediaFull> 
     */
    open class func createAccountMediaTtsWithRequestBuilder(accountId: Int32, data: CreateMediaParams? = nil) -> RequestBuilder<MediaFull> {
        var path = "/accounts/{account_id}/media/tts"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = data?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<MediaFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Delete an individual media record
     
     - parameter accountId: (path) Account ID 
     - parameter mediaId: (path) Media ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteAccountMedia(accountId: Int32, mediaId: Int32, completion: @escaping ((_ data: DeleteEntry?,_ error: Error?) -> Void)) {
        deleteAccountMediaWithRequestBuilder(accountId: accountId, mediaId: mediaId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Delete an individual media record
     - DELETE /accounts/{account_id}/media/{media_id}
     - See Account Media for more info on the properties.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "success" : true
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter mediaId: (path) Media ID 

     - returns: RequestBuilder<DeleteEntry> 
     */
    open class func deleteAccountMediaWithRequestBuilder(accountId: Int32, mediaId: Int32) -> RequestBuilder<DeleteEntry> {
        var path = "/accounts/{account_id}/media/{media_id}"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{media_id}", with: "\(mediaId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<DeleteEntry>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Show details of an individual media recording (Greeting or Hold Music)
     
     - parameter accountId: (path) Account ID 
     - parameter mediaId: (path) Media ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAccountMedia(accountId: Int32, mediaId: Int32, completion: @escaping ((_ data: MediaFull?,_ error: Error?) -> Void)) {
        getAccountMediaWithRequestBuilder(accountId: accountId, mediaId: mediaId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Show details of an individual media recording (Greeting or Hold Music)
     - GET /accounts/{account_id}/media/{media_id}
     - Get individual media recording
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "name" : "aeiou",
  "id" : 0,
  "type" : "aeiou"
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter mediaId: (path) Media ID 

     - returns: RequestBuilder<MediaFull> 
     */
    open class func getAccountMediaWithRequestBuilder(accountId: Int32, mediaId: Int32) -> RequestBuilder<MediaFull> {
        var path = "/accounts/{account_id}/media/{media_id}"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{media_id}", with: "\(mediaId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<MediaFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get a list of media recordings for an account.
     
     - parameter accountId: (path) Account ID 
     - parameter filtersId: (query) ID filter (optional)
     - parameter filtersName: (query) Name filter (optional)
     - parameter sortId: (query) ID sorting (optional)
     - parameter sortName: (query) Name sorting (optional)
     - parameter limit: (query) Max results (optional)
     - parameter offset: (query) Results to skip (optional)
     - parameter fields: (query) Field set (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listAccountMedia(accountId: Int32, filtersId: [String]? = nil, filtersName: [String]? = nil, sortId: String? = nil, sortName: String? = nil, limit: Int32? = nil, offset: Int32? = nil, fields: String? = nil, completion: @escaping ((_ data: ListMedia?,_ error: Error?) -> Void)) {
        listAccountMediaWithRequestBuilder(accountId: accountId, filtersId: filtersId, filtersName: filtersName, sortId: sortId, sortName: sortName, limit: limit, offset: offset, fields: fields).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get a list of media recordings for an account.
     - GET /accounts/{account_id}/media
     - Get a list of media recordings for an account. See Account Media for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level List Media API with the following definition: GET https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/media
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "total" : 0,
  "offset" : 6,
  "limit" : 1,
  "filters" : {
    "name" : "aeiou",
    "id" : "aeiou"
  },
  "sort" : {
    "name" : "aeiou",
    "id" : "aeiou"
  },
  "items" : [ {
    "name" : "aeiou",
    "id" : 5
  } ]
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter filtersId: (query) ID filter (optional)
     - parameter filtersName: (query) Name filter (optional)
     - parameter sortId: (query) ID sorting (optional)
     - parameter sortName: (query) Name sorting (optional)
     - parameter limit: (query) Max results (optional)
     - parameter offset: (query) Results to skip (optional)
     - parameter fields: (query) Field set (optional)

     - returns: RequestBuilder<ListMedia> 
     */
    open class func listAccountMediaWithRequestBuilder(accountId: Int32, filtersId: [String]? = nil, filtersName: [String]? = nil, sortId: String? = nil, sortName: String? = nil, limit: Int32? = nil, offset: Int32? = nil, fields: String? = nil) -> RequestBuilder<ListMedia> {
        var path = "/accounts/{account_id}/media"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "filters[id]": filtersId, 
            "filters[name]": filtersName, 
            "sort[id]": sortId, 
            "sort[name]": sortName, 
            "limit": limit?.encodeToJSON(), 
            "offset": offset?.encodeToJSON(), 
            "fields": fields
        ])
        

        let requestBuilder: RequestBuilder<ListMedia>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Update a media object to your account. Note: The maximum size for media files or JSON objects included with a POST or PUT request is 10 MB.
     
     - parameter accountId: (path) Account ID 
     - parameter mediaId: (path) Media ID 
     - parameter json: (form) Media extra parameters (optional)
     - parameter file: (form) Media file (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func replaceAccountMediaFiles(accountId: Int32, mediaId: Int32, json: String? = nil, file: URL? = nil, completion: @escaping ((_ data: MediaFull?,_ error: Error?) -> Void)) {
        replaceAccountMediaFilesWithRequestBuilder(accountId: accountId, mediaId: mediaId, json: json, file: file).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Update a media object to your account. Note: The maximum size for media files or JSON objects included with a POST or PUT request is 10 MB.
     - PUT /accounts/{account_id}/media/files/{media_id}
     - See Account Media for more info on the properties.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "name" : "aeiou",
  "id" : 0,
  "type" : "aeiou"
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter mediaId: (path) Media ID 
     - parameter json: (form) Media extra parameters (optional)
     - parameter file: (form) Media file (optional)

     - returns: RequestBuilder<MediaFull> 
     */
    open class func replaceAccountMediaFilesWithRequestBuilder(accountId: Int32, mediaId: Int32, json: String? = nil, file: URL? = nil) -> RequestBuilder<MediaFull> {
        var path = "/accounts/{account_id}/media/files/{media_id}"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{media_id}", with: "\(mediaId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let formParams: [String:Any?] = [
            "json": json,
            "file": file
        ]

        let nonNullParameters = APIHelper.rejectNil(formParams)
        let parameters = APIHelper.convertBoolToString(nonNullParameters)

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<MediaFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Update a media object to your account.
     
     - parameter accountId: (path) Account ID 
     - parameter mediaId: (path) Media ID 
     - parameter data: (body) Media data (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func replaceAccountMediaTts(accountId: Int32, mediaId: Int32, data: CreateMediaParams? = nil, completion: @escaping ((_ data: MediaFull?,_ error: Error?) -> Void)) {
        replaceAccountMediaTtsWithRequestBuilder(accountId: accountId, mediaId: mediaId, data: data).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Update a media object to your account.
     - PUT /accounts/{account_id}/media/tts/{media_id}
     - Update a media object to your account. Note: The maximum size for media files or JSON objects included with a POST or PUT request is 10 MB. See Account Media for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level Replace Media API with the following definition: PUT https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/media/:media_id
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "name" : "aeiou",
  "id" : 0,
  "type" : "aeiou"
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter mediaId: (path) Media ID 
     - parameter data: (body) Media data (optional)

     - returns: RequestBuilder<MediaFull> 
     */
    open class func replaceAccountMediaTtsWithRequestBuilder(accountId: Int32, mediaId: Int32, data: CreateMediaParams? = nil) -> RequestBuilder<MediaFull> {
        var path = "/accounts/{account_id}/media/tts/{media_id}"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{media_id}", with: "\(mediaId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = data?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<MediaFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
