//
// MenusAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class MenusAPI: APIBase {
    /**
     Create an individual menu.
     
     - parameter accountId: (path) Account ID 
     - parameter data: (body) Menu data (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createAccountMenu(accountId: Int32, data: CreateMenuParams? = nil, completion: @escaping ((_ data: MenuFull?,_ error: Error?) -> Void)) {
        createAccountMenuWithRequestBuilder(accountId: accountId, data: data).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Create an individual menu.
     - POST /accounts/{account_id}/menus
     - Create an individual menu. See Account Menus for more info on the properties.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "allow_extension_dial" : true,
  "greeting" : {
    "name" : "aeiou",
    "id" : 1
  },
  "timeout_handler" : {
    "name" : "aeiou",
    "id" : 5
  },
  "name" : "aeiou",
  "options" : [ {
    "route" : "",
    "key" : "aeiou"
  } ],
  "id" : 0,
  "keypress_wait_time" : 6,
  "keypress_error" : ""
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter data: (body) Menu data (optional)

     - returns: RequestBuilder<MenuFull> 
     */
    open class func createAccountMenuWithRequestBuilder(accountId: Int32, data: CreateMenuParams? = nil) -> RequestBuilder<MenuFull> {
        var path = "/accounts/{account_id}/menus"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = data?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<MenuFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Delete an individual menu.
     
     - parameter accountId: (path) Account ID 
     - parameter menuId: (path) Menu ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteAccountMenu(accountId: Int32, menuId: Int32, completion: @escaping ((_ data: DeleteEntry?,_ error: Error?) -> Void)) {
        deleteAccountMenuWithRequestBuilder(accountId: accountId, menuId: menuId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Delete an individual menu.
     - DELETE /accounts/{account_id}/menus/{menu_id}
     - Delete an individual menu. See Account Menus for more info on the properties.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "success" : true
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter menuId: (path) Menu ID 

     - returns: RequestBuilder<DeleteEntry> 
     */
    open class func deleteAccountMenuWithRequestBuilder(accountId: Int32, menuId: Int32) -> RequestBuilder<DeleteEntry> {
        var path = "/accounts/{account_id}/menus/{menu_id}"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{menu_id}", with: "\(menuId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<DeleteEntry>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Show details of an individual menu.
     
     - parameter accountId: (path) Account ID 
     - parameter menuId: (path) Menu ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAccountMenu(accountId: Int32, menuId: Int32, completion: @escaping ((_ data: MenuFull?,_ error: Error?) -> Void)) {
        getAccountMenuWithRequestBuilder(accountId: accountId, menuId: menuId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Show details of an individual menu.
     - GET /accounts/{account_id}/menus/{menu_id}
     - Show details of an individual menu. See Account Menus for more info on the properties.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "allow_extension_dial" : true,
  "greeting" : {
    "name" : "aeiou",
    "id" : 1
  },
  "timeout_handler" : {
    "name" : "aeiou",
    "id" : 5
  },
  "name" : "aeiou",
  "options" : [ {
    "route" : "",
    "key" : "aeiou"
  } ],
  "id" : 0,
  "keypress_wait_time" : 6,
  "keypress_error" : ""
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter menuId: (path) Menu ID 

     - returns: RequestBuilder<MenuFull> 
     */
    open class func getAccountMenuWithRequestBuilder(accountId: Int32, menuId: Int32) -> RequestBuilder<MenuFull> {
        var path = "/accounts/{account_id}/menus/{menu_id}"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{menu_id}", with: "\(menuId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<MenuFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get a list of menus for an account.
     
     - parameter accountId: (path) Account ID 
     - parameter filtersId: (query) ID filter (optional)
     - parameter filtersName: (query) Name filter (optional)
     - parameter sortId: (query) ID sorting (optional)
     - parameter sortName: (query) Name sorting (optional)
     - parameter limit: (query) Max results (optional)
     - parameter offset: (query) Results to skip (optional)
     - parameter fields: (query) Field set (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listAccountMenus(accountId: Int32, filtersId: [String]? = nil, filtersName: [String]? = nil, sortId: String? = nil, sortName: String? = nil, limit: Int32? = nil, offset: Int32? = nil, fields: String? = nil, completion: @escaping ((_ data: ListMenus?,_ error: Error?) -> Void)) {
        listAccountMenusWithRequestBuilder(accountId: accountId, filtersId: filtersId, filtersName: filtersName, sortId: sortId, sortName: sortName, limit: limit, offset: offset, fields: fields).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get a list of menus for an account.
     - GET /accounts/{account_id}/menus
     - Get a list of menus for an account. See Account Menus for more info on the properties.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "total" : 0,
  "offset" : 6,
  "limit" : 1,
  "filters" : {
    "name" : "aeiou",
    "id" : "aeiou"
  },
  "sort" : {
    "name" : "aeiou",
    "id" : "aeiou"
  },
  "items" : [ {
    "allow_extension_dial" : true,
    "greeting" : {
      "name" : "aeiou",
      "id" : 2
    },
    "timeout_handler" : {
      "name" : "aeiou",
      "id" : 7
    },
    "name" : "aeiou",
    "options" : [ {
      "route" : "",
      "key" : "aeiou"
    } ],
    "id" : 5,
    "keypress_wait_time" : 5,
    "keypress_error" : ""
  } ]
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter filtersId: (query) ID filter (optional)
     - parameter filtersName: (query) Name filter (optional)
     - parameter sortId: (query) ID sorting (optional)
     - parameter sortName: (query) Name sorting (optional)
     - parameter limit: (query) Max results (optional)
     - parameter offset: (query) Results to skip (optional)
     - parameter fields: (query) Field set (optional)

     - returns: RequestBuilder<ListMenus> 
     */
    open class func listAccountMenusWithRequestBuilder(accountId: Int32, filtersId: [String]? = nil, filtersName: [String]? = nil, sortId: String? = nil, sortName: String? = nil, limit: Int32? = nil, offset: Int32? = nil, fields: String? = nil) -> RequestBuilder<ListMenus> {
        var path = "/accounts/{account_id}/menus"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "filters[id]": filtersId, 
            "filters[name]": filtersName, 
            "sort[id]": sortId, 
            "sort[name]": sortName, 
            "limit": limit?.encodeToJSON(), 
            "offset": offset?.encodeToJSON(), 
            "fields": fields
        ])
        

        let requestBuilder: RequestBuilder<ListMenus>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Replace an individual menu.
     
     - parameter accountId: (path) Account ID 
     - parameter menuId: (path) Menu ID 
     - parameter data: (body) Menu data (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func replaceAccountMenu(accountId: Int32, menuId: Int32, data: ReplaceMenuParams? = nil, completion: @escaping ((_ data: MenuFull?,_ error: Error?) -> Void)) {
        replaceAccountMenuWithRequestBuilder(accountId: accountId, menuId: menuId, data: data).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Replace an individual menu.
     - PUT /accounts/{account_id}/menus/{menu_id}
     - Replace an individual menu. See Account Menus for more info on the properties.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "allow_extension_dial" : true,
  "greeting" : {
    "name" : "aeiou",
    "id" : 1
  },
  "timeout_handler" : {
    "name" : "aeiou",
    "id" : 5
  },
  "name" : "aeiou",
  "options" : [ {
    "route" : "",
    "key" : "aeiou"
  } ],
  "id" : 0,
  "keypress_wait_time" : 6,
  "keypress_error" : ""
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter menuId: (path) Menu ID 
     - parameter data: (body) Menu data (optional)

     - returns: RequestBuilder<MenuFull> 
     */
    open class func replaceAccountMenuWithRequestBuilder(accountId: Int32, menuId: Int32, data: ReplaceMenuParams? = nil) -> RequestBuilder<MenuFull> {
        var path = "/accounts/{account_id}/menus/{menu_id}"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{menu_id}", with: "\(menuId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = data?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<MenuFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
