//
// OauthAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class OauthAPI: APIBase {
    /**
     To create an access token via the /oauth/access-token API, an API user may choose any one of the grant types it supports: Authorization Code Grant, Client Credential Grant, Password Credential Grant or Refresh Token Grant.
     
     - parameter data: (body) Oauth data (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createOauthAccessToken(data: CreateOauthParams? = nil, completion: @escaping ((_ data: OauthAccessToken?,_ error: Error?) -> Void)) {
        createOauthAccessTokenWithRequestBuilder(data: data).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     To create an access token via the /oauth/access-token API, an API user may choose any one of the grant types it supports: Authorization Code Grant, Client Credential Grant, Password Credential Grant or Refresh Token Grant.
     - POST /oauth/access-token
     - To create an access token via the /oauth/access-token API, an API user may choose any one of the grant types it supports: Authorization Code Grant, Client Credential Grant, Password Credential Grant or Refresh Token Grant. For Authorization Code Grant, the input parameter 'code' is generated via the Create Authorization API. NOTE: The Create Access Token API now accepts requests in query string format as well as JSON body format. See OAuth for more details on how to obtain client id and client secret to create an access token at real time.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "access_token" : "aeiou",
  "refresh_token" : "aeiou",
  "scope" : "aeiou",
  "token_type" : "aeiou",
  "expires_in" : 0
}}]
     
     - parameter data: (body) Oauth data (optional)

     - returns: RequestBuilder<OauthAccessToken> 
     */
    open class func createOauthAccessTokenWithRequestBuilder(data: CreateOauthParams? = nil) -> RequestBuilder<OauthAccessToken> {
        let path = "/oauth/access-token"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = data?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<OauthAccessToken>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Create Authorization Code or Access Token.
     
     - parameter clientId: (query) Client ID 
     - parameter responseType: (query) &#39;token&#39; for Implicit Grant; &#39;code&#39; for Authorization Code Grant 
     - parameter scope: (query) account-owner, extension-user and/or methods:ALL, separated by space (%20) 
     - parameter redirectUri: (query) The URL where the response data of this API is redirected to 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createOauthAuthorization(clientId: String, responseType: String, scope: String, redirectUri: String, completion: @escaping ((_ error: Error?) -> Void)) {
        createOauthAuthorizationWithRequestBuilder(clientId: clientId, responseType: responseType, scope: scope, redirectUri: redirectUri).execute { (response, error) -> Void in
            completion(error);
        }
    }


    /**
     Create Authorization Code or Access Token.
     - GET /oauth/authorization
     - Create Authorization Code or Access Token. The /oauth/authorization API supports Authorization Grant and Implicit Grant. In Authorization Grant, this API returns a code (response_type=code) for clients implemented in a browser using a scripting language such as JavaScript. Users may then use the code via the Create Access Token API to create an access token. The Implicit Grant is a simplified authorization code flow. In the implicit flow, instead of issuing the client an authorization code, the client is issued an access token (response_type=token) directly. See OAuth for more details on how to obtain client id and client secret to create authorization code access token at real time.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     
     - parameter clientId: (query) Client ID 
     - parameter responseType: (query) &#39;token&#39; for Implicit Grant; &#39;code&#39; for Authorization Code Grant 
     - parameter scope: (query) account-owner, extension-user and/or methods:ALL, separated by space (%20) 
     - parameter redirectUri: (query) The URL where the response data of this API is redirected to 

     - returns: RequestBuilder<Void> 
     */
    open class func createOauthAuthorizationWithRequestBuilder(clientId: String, responseType: String, scope: String, redirectUri: String) -> RequestBuilder<Void> {
        let path = "/oauth/authorization"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "client_id": clientId, 
            "response_type": responseType, 
            "scope": scope, 
            "redirect_uri": redirectUri
        ])
        

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Retrieve details of an access token, such as scope, expiration and extension ID.
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getOauthAccessToken(completion: @escaping ((_ data: GetOauthAccessToken?,_ error: Error?) -> Void)) {
        getOauthAccessTokenWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Retrieve details of an access token, such as scope, expiration and extension ID.
     - GET /oauth/access-token
     - Retrieve details of an access token, such as scope, expiration and extension ID. Voip ID will be returned as well if scope contains account-owner scope.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "expires_at" : 0,
  "scope_details" : [ {
    "voip_id" : 6
  } ],
  "scope" : "aeiou"
}}]

     - returns: RequestBuilder<GetOauthAccessToken> 
     */
    open class func getOauthAccessTokenWithRequestBuilder() -> RequestBuilder<GetOauthAccessToken> {
        let path = "/oauth/access-token"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<GetOauthAccessToken>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
