//
// OauthclientsredirecturisAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class OauthclientsredirecturisAPI: APIBase {
    /**
     Create an OAuth Client Redirect URI record.
     
     - parameter accountId: (path) Account ID 
     - parameter clientId: (path) Client ID 
     - parameter data: (body) Redirect Uri data (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createAccountOauthClientsRedirectUri(accountId: Int32, clientId: Int32, data: CreateRedirectUriParams? = nil, completion: @escaping ((_ data: OauthClientRedirectUriFull?,_ error: Error?) -> Void)) {
        createAccountOauthClientsRedirectUriWithRequestBuilder(accountId: accountId, clientId: clientId, data: data).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Create an OAuth Client Redirect URI record.
     - POST /accounts/{account_id}/oauth/clients/{client_id}/redirect-uris
     - Create an OAuth Client Redirect URI record.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "client" : {
    "id" : 6,
    "client_name" : "aeiou"
  },
  "id" : 0,
  "redirect_uri" : {
    "id" : 1,
    "type" : "aeiou",
    "uri" : "aeiou"
  }
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter clientId: (path) Client ID 
     - parameter data: (body) Redirect Uri data (optional)

     - returns: RequestBuilder<OauthClientRedirectUriFull> 
     */
    open class func createAccountOauthClientsRedirectUriWithRequestBuilder(accountId: Int32, clientId: Int32, data: CreateRedirectUriParams? = nil) -> RequestBuilder<OauthClientRedirectUriFull> {
        var path = "/accounts/{account_id}/oauth/clients/{client_id}/redirect-uris"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{client_id}", with: "\(clientId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = data?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<OauthClientRedirectUriFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Delete an OAuth Client Redirect URI record.
     
     - parameter accountId: (path) Account ID 
     - parameter clientId: (path) Client ID 
     - parameter uriId: (path) Redirect URI ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteAccountOauthClientsRedirectUri(accountId: Int32, clientId: Int32, uriId: Int32, completion: @escaping ((_ data: DeleteEntry?,_ error: Error?) -> Void)) {
        deleteAccountOauthClientsRedirectUriWithRequestBuilder(accountId: accountId, clientId: clientId, uriId: uriId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Delete an OAuth Client Redirect URI record.
     - DELETE /accounts/{account_id}/oauth/clients/{client_id}/redirect-uris/{uri_id}
     - Delete an OAuth Client Redirect URI record.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "success" : true
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter clientId: (path) Client ID 
     - parameter uriId: (path) Redirect URI ID 

     - returns: RequestBuilder<DeleteEntry> 
     */
    open class func deleteAccountOauthClientsRedirectUriWithRequestBuilder(accountId: Int32, clientId: Int32, uriId: Int32) -> RequestBuilder<DeleteEntry> {
        var path = "/accounts/{account_id}/oauth/clients/{client_id}/redirect-uris/{uri_id}"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{client_id}", with: "\(clientId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{uri_id}", with: "\(uriId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<DeleteEntry>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get details of an OAuth Client Redirect URI record.
     
     - parameter accountId: (path) Account ID 
     - parameter clientId: (path) Client ID 
     - parameter uriId: (path) Redirect URI ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAccountOauthClientsRedirectUri(accountId: Int32, clientId: Int32, uriId: Int32, completion: @escaping ((_ data: OauthClientRedirectUriFull?,_ error: Error?) -> Void)) {
        getAccountOauthClientsRedirectUriWithRequestBuilder(accountId: accountId, clientId: clientId, uriId: uriId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get details of an OAuth Client Redirect URI record.
     - GET /accounts/{account_id}/oauth/clients/{client_id}/redirect-uris/{uri_id}
     - Get details of an OAuth Client Redirect URI record.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "client" : {
    "id" : 6,
    "client_name" : "aeiou"
  },
  "id" : 0,
  "redirect_uri" : {
    "id" : 1,
    "type" : "aeiou",
    "uri" : "aeiou"
  }
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter clientId: (path) Client ID 
     - parameter uriId: (path) Redirect URI ID 

     - returns: RequestBuilder<OauthClientRedirectUriFull> 
     */
    open class func getAccountOauthClientsRedirectUriWithRequestBuilder(accountId: Int32, clientId: Int32, uriId: Int32) -> RequestBuilder<OauthClientRedirectUriFull> {
        var path = "/accounts/{account_id}/oauth/clients/{client_id}/redirect-uris/{uri_id}"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{client_id}", with: "\(clientId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{uri_id}", with: "\(uriId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<OauthClientRedirectUriFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get a list of OAuth Client Redirect URIs for an account.
     
     - parameter accountId: (path) Account ID 
     - parameter clientId: (path) Client ID 
     - parameter filtersId: (query) ID filter (optional)
     - parameter sortId: (query) ID sorting (optional)
     - parameter limit: (query) Max results (optional)
     - parameter offset: (query) Results to skip (optional)
     - parameter fields: (query) Field set (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listAccountOauthClientsRedirectUris(accountId: Int32, clientId: Int32, filtersId: [String]? = nil, sortId: String? = nil, limit: Int32? = nil, offset: Int32? = nil, fields: String? = nil, completion: @escaping ((_ data: ListOauthClientsRedirectUris?,_ error: Error?) -> Void)) {
        listAccountOauthClientsRedirectUrisWithRequestBuilder(accountId: accountId, clientId: clientId, filtersId: filtersId, sortId: sortId, limit: limit, offset: offset, fields: fields).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get a list of OAuth Client Redirect URIs for an account.
     - GET /accounts/{account_id}/oauth/clients/{client_id}/redirect-uris
     - Get a list of OAuth Client Redirect URIs for an account.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "total" : 0,
  "offset" : 6,
  "limit" : 1,
  "filters" : {
    "id" : "aeiou"
  },
  "items" : [ {
    "client" : {
      "id" : 5,
      "client_name" : "aeiou"
    },
    "id" : 5,
    "redirect_uri" : {
      "id" : 2,
      "type" : "aeiou",
      "uri" : "aeiou"
    }
  } ]
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter clientId: (path) Client ID 
     - parameter filtersId: (query) ID filter (optional)
     - parameter sortId: (query) ID sorting (optional)
     - parameter limit: (query) Max results (optional)
     - parameter offset: (query) Results to skip (optional)
     - parameter fields: (query) Field set (optional)

     - returns: RequestBuilder<ListOauthClientsRedirectUris> 
     */
    open class func listAccountOauthClientsRedirectUrisWithRequestBuilder(accountId: Int32, clientId: Int32, filtersId: [String]? = nil, sortId: String? = nil, limit: Int32? = nil, offset: Int32? = nil, fields: String? = nil) -> RequestBuilder<ListOauthClientsRedirectUris> {
        var path = "/accounts/{account_id}/oauth/clients/{client_id}/redirect-uris"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{client_id}", with: "\(clientId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "filters[id]": filtersId, 
            "sort[id]": sortId, 
            "limit": limit?.encodeToJSON(), 
            "offset": offset?.encodeToJSON(), 
            "fields": fields
        ])
        

        let requestBuilder: RequestBuilder<ListOauthClientsRedirectUris>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
