//
// SubaccountsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SubaccountsAPI: APIBase {
    /**
     Add a subaccount for the authenticated user or client
     
     - parameter accountId: (path) Account ID 
     - parameter data: (body) Subaccount data 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createAccountSubaccount(accountId: Int32, data: CreateSubaccountParams, completion: @escaping ((_ data: AccountFull?,_ error: Error?) -> Void)) {
        createAccountSubaccountWithRequestBuilder(accountId: accountId, data: data).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Add a subaccount for the authenticated user or client
     - POST /accounts/{account_id}/subaccounts
     - Add a subaccount for the authenticated user or client
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "password" : "aeiou",
  "billing_contact" : "",
  "contact" : {
    "address" : {
      "line_1" : "aeiou",
      "line_2" : "aeiou",
      "country" : "aeiou",
      "province" : "aeiou",
      "city" : "aeiou",
      "postal_code" : "aeiou"
    },
    "phone" : "aeiou",
    "name" : "aeiou",
    "company" : "aeiou",
    "primary_email" : "aeiou",
    "fax" : "aeiou",
    "alternate_email" : "aeiou"
  },
  "name" : "aeiou",
  "master_account" : {
    "name" : "aeiou",
    "id" : 6
  },
  "id" : 0,
  "username" : "aeiou"
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter data: (body) Subaccount data 

     - returns: RequestBuilder<AccountFull> 
     */
    open class func createAccountSubaccountWithRequestBuilder(accountId: Int32, data: CreateSubaccountParams) -> RequestBuilder<AccountFull> {
        var path = "/accounts/{account_id}/subaccounts"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = data.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<AccountFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Get a list of subaccounts for the authenticated user or client
     
     - parameter accountId: (path) Account ID 
     - parameter filtersId: (query) ID filter (optional)
     - parameter sortId: (query) ID sorting (optional)
     - parameter limit: (query) Max results (optional)
     - parameter offset: (query) Results to skip (optional)
     - parameter fields: (query) Field set (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listAccountSubaccounts(accountId: Int32, filtersId: [String]? = nil, sortId: String? = nil, limit: Int32? = nil, offset: Int32? = nil, fields: String? = nil, completion: @escaping ((_ data: ListAccounts?,_ error: Error?) -> Void)) {
        listAccountSubaccountsWithRequestBuilder(accountId: accountId, filtersId: filtersId, sortId: sortId, limit: limit, offset: offset, fields: fields).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get a list of subaccounts for the authenticated user or client
     - GET /accounts/{account_id}/subaccounts
     - Get a list of subaccounts for the authenticated user or client
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "total" : 0,
  "offset" : 6,
  "limit" : 1,
  "filters" : {
    "id" : "aeiou"
  },
  "sort" : {
    "id" : "aeiou"
  },
  "items" : [ {
    "password" : "aeiou",
    "billing_contact" : "",
    "contact" : {
      "address" : {
        "line_1" : "aeiou",
        "line_2" : "aeiou",
        "country" : "aeiou",
        "province" : "aeiou",
        "city" : "aeiou",
        "postal_code" : "aeiou"
      },
      "phone" : "aeiou",
      "name" : "aeiou",
      "company" : "aeiou",
      "primary_email" : "aeiou",
      "fax" : "aeiou",
      "alternate_email" : "aeiou"
    },
    "name" : "aeiou",
    "master_account" : {
      "name" : "aeiou",
      "id" : 5
    },
    "id" : 5,
    "username" : "aeiou"
  } ]
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter filtersId: (query) ID filter (optional)
     - parameter sortId: (query) ID sorting (optional)
     - parameter limit: (query) Max results (optional)
     - parameter offset: (query) Results to skip (optional)
     - parameter fields: (query) Field set (optional)

     - returns: RequestBuilder<ListAccounts> 
     */
    open class func listAccountSubaccountsWithRequestBuilder(accountId: Int32, filtersId: [String]? = nil, sortId: String? = nil, limit: Int32? = nil, offset: Int32? = nil, fields: String? = nil) -> RequestBuilder<ListAccounts> {
        var path = "/accounts/{account_id}/subaccounts"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "filters[id]": filtersId, 
            "sort[id]": sortId, 
            "limit": limit?.encodeToJSON(), 
            "offset": offset?.encodeToJSON(), 
            "fields": fields
        ])
        

        let requestBuilder: RequestBuilder<ListAccounts>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
