//
// VoicemailAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class VoicemailAPI: APIBase {
    /**
     This service shows the details of an individual voicemail.
     
     - parameter accountId: (path) Account ID 
     - parameter voicemailId: (path) Voicemail ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAccountVoicemail(accountId: Int32, voicemailId: String, completion: @escaping ((_ data: VoicemailFull?,_ error: Error?) -> Void)) {
        getAccountVoicemailWithRequestBuilder(accountId: accountId, voicemailId: voicemailId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     This service shows the details of an individual voicemail.
     - GET /accounts/{account_id}/voicemail/{voicemail_id}
     - This service shows the details of an individual voicemail. See Intro to Voicemail for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Get Voicemail API with the following definition: GET https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/voicemail/:voicemail_id
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "duration" : 5,
  "extension" : {
    "extension" : 6,
    "name" : "aeiou",
    "id" : 0
  },
  "folder" : "aeiou",
  "is_new" : true,
  "download_url" : "aeiou",
  "created_at" : 1,
  "from" : {
    "number" : "aeiou",
    "city" : "aeiou",
    "name" : "aeiou",
    "state" : "aeiou"
  },
  "id" : "aeiou",
  "to" : "aeiou"
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter voicemailId: (path) Voicemail ID 

     - returns: RequestBuilder<VoicemailFull> 
     */
    open class func getAccountVoicemailWithRequestBuilder(accountId: Int32, voicemailId: String) -> RequestBuilder<VoicemailFull> {
        var path = "/accounts/{account_id}/voicemail/{voicemail_id}"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{voicemail_id}", with: "\(voicemailId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<VoicemailFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get a list of voicemail messages for an account.
     
     - parameter accountId: (path) Account ID 
     - parameter filtersId: (query) ID filter (optional)
     - parameter filtersFrom: (query) Caller ID filter (optional)
     - parameter filtersTo: (query) Callee ID filter, the E.164 phone number to send the SMS TO. Note you must encode the + as %2B (optional)
     - parameter filtersIsNew: (query)  (optional)
     - parameter filtersCreatedAt: (query) Date string representing the UTC time that sms was created (optional)
     - parameter filtersExtension: (query) Extension filter (optional)
     - parameter sortId: (query) ID sorting (optional)
     - parameter sortCreatedAt: (query) Sort by the UTC time that voicemail was created (optional)
     - parameter limit: (query) Max results (optional)
     - parameter offset: (query) Results to skip (optional)
     - parameter fields: (query) Field set (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func listAccountVoicemail(accountId: Int32, filtersId: [String]? = nil, filtersFrom: String? = nil, filtersTo: String? = nil, filtersIsNew: Bool? = nil, filtersCreatedAt: String? = nil, filtersExtension: [String]? = nil, sortId: String? = nil, sortCreatedAt: String? = nil, limit: Int32? = nil, offset: Int32? = nil, fields: String? = nil, completion: @escaping ((_ data: ListVoicemail?,_ error: Error?) -> Void)) {
        listAccountVoicemailWithRequestBuilder(accountId: accountId, filtersId: filtersId, filtersFrom: filtersFrom, filtersTo: filtersTo, filtersIsNew: filtersIsNew, filtersCreatedAt: filtersCreatedAt, filtersExtension: filtersExtension, sortId: sortId, sortCreatedAt: sortCreatedAt, limit: limit, offset: offset, fields: fields).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get a list of voicemail messages for an account.
     - GET /accounts/{account_id}/voicemail
     - Get a list of voicemail messages for an account. See Intro to Voicemail for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the List Voicemail API with the following definition: GET https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/voicemail
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "total" : 6,
  "offset" : 1,
  "limit" : 5,
  "filters" : {
    "extension" : "aeiou",
    "is_new" : "aeiou",
    "created_at" : 0,
    "from" : "aeiou",
    "id" : "aeiou",
    "to" : "aeiou"
  },
  "sort" : {
    "created_at" : "aeiou",
    "id" : "aeiou"
  },
  "items" : [ {
    "duration" : 9,
    "extension" : {
      "extension" : 2,
      "name" : "aeiou",
      "id" : 5
    },
    "folder" : "aeiou",
    "is_new" : true,
    "download_url" : "aeiou",
    "created_at" : 7,
    "from" : {
      "number" : "aeiou",
      "city" : "aeiou",
      "name" : "aeiou",
      "state" : "aeiou"
    },
    "id" : "aeiou",
    "to" : "aeiou"
  } ]
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter filtersId: (query) ID filter (optional)
     - parameter filtersFrom: (query) Caller ID filter (optional)
     - parameter filtersTo: (query) Callee ID filter, the E.164 phone number to send the SMS TO. Note you must encode the + as %2B (optional)
     - parameter filtersIsNew: (query)  (optional)
     - parameter filtersCreatedAt: (query) Date string representing the UTC time that sms was created (optional)
     - parameter filtersExtension: (query) Extension filter (optional)
     - parameter sortId: (query) ID sorting (optional)
     - parameter sortCreatedAt: (query) Sort by the UTC time that voicemail was created (optional)
     - parameter limit: (query) Max results (optional)
     - parameter offset: (query) Results to skip (optional)
     - parameter fields: (query) Field set (optional)

     - returns: RequestBuilder<ListVoicemail> 
     */
    open class func listAccountVoicemailWithRequestBuilder(accountId: Int32, filtersId: [String]? = nil, filtersFrom: String? = nil, filtersTo: String? = nil, filtersIsNew: Bool? = nil, filtersCreatedAt: String? = nil, filtersExtension: [String]? = nil, sortId: String? = nil, sortCreatedAt: String? = nil, limit: Int32? = nil, offset: Int32? = nil, fields: String? = nil) -> RequestBuilder<ListVoicemail> {
        var path = "/accounts/{account_id}/voicemail"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "filters[id]": filtersId, 
            "filters[from]": filtersFrom, 
            "filters[to]": filtersTo, 
            "filters[is_new]": filtersIsNew, 
            "filters[created_at]": filtersCreatedAt, 
            "filters[extension]": filtersExtension, 
            "sort[id]": sortId, 
            "sort[created_at]": sortCreatedAt, 
            "limit": limit?.encodeToJSON(), 
            "offset": offset?.encodeToJSON(), 
            "fields": fields
        ])
        

        let requestBuilder: RequestBuilder<ListVoicemail>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Update the is_new parameter in a voicemail record.
     
     - parameter accountId: (path) Account ID 
     - parameter voicemailId: (path) Voicemail ID 
     - parameter data: (body) Payment data (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func patchAccountVoicemail(accountId: Int32, voicemailId: String, data: PatchVoicemailParams? = nil, completion: @escaping ((_ data: VoicemailFull?,_ error: Error?) -> Void)) {
        patchAccountVoicemailWithRequestBuilder(accountId: accountId, voicemailId: voicemailId, data: data).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Update the is_new parameter in a voicemail record.
     - PATCH /accounts/{account_id}/voicemail/{voicemail_id}
     - Update the is_new parameter in a voicemail record. See Account Voicemail for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Patch Voicemail API with the following definition: PATCH https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/voicemail/:voicemail_id
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "duration" : 5,
  "extension" : {
    "extension" : 6,
    "name" : "aeiou",
    "id" : 0
  },
  "folder" : "aeiou",
  "is_new" : true,
  "download_url" : "aeiou",
  "created_at" : 1,
  "from" : {
    "number" : "aeiou",
    "city" : "aeiou",
    "name" : "aeiou",
    "state" : "aeiou"
  },
  "id" : "aeiou",
  "to" : "aeiou"
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter voicemailId: (path) Voicemail ID 
     - parameter data: (body) Payment data (optional)

     - returns: RequestBuilder<VoicemailFull> 
     */
    open class func patchAccountVoicemailWithRequestBuilder(accountId: Int32, voicemailId: String, data: PatchVoicemailParams? = nil) -> RequestBuilder<VoicemailFull> {
        var path = "/accounts/{account_id}/voicemail/{voicemail_id}"
        path = path.replacingOccurrences(of: "{account_id}", with: "\(accountId)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{voicemail_id}", with: "\(voicemailId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = data?.encodeToJSON() as? [String:AnyObject]

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<VoicemailFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
